language: cpp
dist: xenial
git:
  depth: 1
env:
  global:
  - BUILD_CONFIG=Release
jobs:
  include:
  - name: "Windows 10"
    os: windows
  - name: "Xenial GCC5"
    os: linux
    compiler: gcc
  - name: "Xenial LLVM7"
    os: linux
    compiler: clang
  - name: "Mojave"
    os: osx
    osx_image: xcode10.3
    env: MACOSX_DEPLOYMENT_TARGET=10.11
script:
- mkdir -p build && cd build
- cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIG && cmake --build . --config $BUILD_CONFIG --parallel 2
- cd ..
before_deploy:
- mkdir -p ygopen-netdecker && cp LICENSE README.md ygopen-netdecker
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    mv build/$BUILD_CONFIG/ygopen-netdecker.exe ygopen-netdecker;
    powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Compress-Archive -Path ygopen-netdecker -DestinationPath ygopen-netdecker-$TRAVIS_OS_NAME";
  else
    mv build/ygopen-netdecker ygopen-netdecker/ygopen-netdecker;
    tar -zcf ygopen-netdecker-$TRAVIS_OS_NAME.tar.gz ygopen-netdecker;
  fi
deploy:
- provider: releases
  api_key: $OAUTH_TOKEN
  overwrite: true
  skip_cleanup: true
  file:
  - ygopen-netdecker-$TRAVIS_OS_NAME.zip
  - ygopen-netdecker-$TRAVIS_OS_NAME.tar.gz
  on:
    condition: '"$TRAVIS_JOB_NAME" != "Xenial LLVM7"'
    tags: true
